name: Node.js CI/CD

on:
  push:
    branches:
      - main  # triggers on push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # set your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build (if applicable)
        run: npm run build  # remove if you don't have a build script

      # Optional deployment step - customize as needed
      - name: Deploy
        run: |
          echo "Deploying app..."
          # Add your deploy commands here